name: NodeJS with Webpack

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npx webpack
      - name: Xanitizer Security Analysis
        uses: RIGS-IT/xanitizer-action@v1.0.1
        with:
          license:
          licenseServerRetryCount:
          checkoutPath:
          overviewReportOutputFile:
          overviewReportOutputFiles:
          findingsListReportOutputFile:
          findingsListReportOutputFiles:
          onlyProblemsInFindingsListReport:
          generateDetailsInFindingsListReport:
          configFile:
          rootDirectory:
          projectName:
          configFileDirectory:
          overwriteConfigFile:
          compileToJavaScript:
          performNodeAudit:
          haltOnMissingSearchPaths:
          haltOnIssues:
          haltOnFindings:
          findingsRatingThreshold:
          updateOwaspDependencyCheckRepository:
          logLevel:
          projectDataDirectory:
          haltOnNewFindings:
          newFindingsRatingThreshold:
          mavenRepository:
          createSnapshot:
          snapshotComment:
          exportDirectory:
          exportSnapshots:
          exportPassphrase:
          mergedProject:
          importPassphrase:
          proxyServer:
          proxyPort:
          proxyUser:
          proxyPassword:
